#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman.config.logger = Logger.new("log/mailman.log")

# Mailman.config.poll_interval = 7

Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 993, ssl: true,
  username: "79653827089a@gmail.com",
  password: "796538270891"
}


Mailman::Application.run do
  default do
    Dialog.create mail: message.body.decoded
  end
end

#
#
# Mailman::Application.run do
#   default do
#     begin
#       Dialog.receive_mail(message)
#     rescue Exception => e
#       Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
#       Mailman.logger.error [e, *e.backtrace].join("\n")
#     end
#   end
# end
